format = """\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $package\
    $elixir\
    $elm\
    $golang\
    $haskell\
    $nodejs\
    $python\
    $ruby\
    $rust\
    $terraform\
    $conda\
    $memory_usage\
    $env_var\
    $line_break\
    $jobs\
    $cmd_duration\
    $time\
    $username\
    $hostname\
    $directory\
    $character\
"""

[character]
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 1
truncate_to_repo = false
fish_style_pwd_dir_length=1
