- name: Install fish, hub, sysstat, fortune-mod, inetutils
  become: true
  pacman:
    name:
      - fish
      - sysstat
      - fortune-mod
      - inetutils

- name: Install fisher, virtualfish, starship
  become: true
  become_user: aur_builder
  aur:
    name:
      - fisher
      - python-virtualfish
      - starship
    skip_installed: true
