- name: Install fish, hub, sysstat, fortune-mod, inetutils, pyenv
  become: true
  pacman:
    name:
      - fish
      - sysstat
      - fortune-mod
      - inetutils
      - pyenv

- name: Install fisher, virtualfish, starship, pfetch
  become: true
  become_user: aur_builder
  aur:
    name:
      - fisher
      - virtualfish
      - starship
      - pfetch
    skip_installed: true
