- import_tasks: arch.yml
  when: ansible_facts['os_family']|lower|replace(' ', '') == 'archlinux'

- name: Make ranger dir
  file:
    state: directory
    path: "{{user_config_dir}}/ranger/"

- name: Symlink rc.conf
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/ranger/rc.conf"
    dest: "{{user_config_dir}}/ranger/rc.conf"

- name: Symlink scope.sh
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/ranger/scope.sh"
    dest: "{{user_config_dir}}/ranger/scope.sh"
