- name: Install ranger and w3m
  become: true
  pacman:
    name: 
      - ranger
      - w3m

- name: Symlink rc.conf
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/ranger/rc.conf"
    dest: "{{user_config_dir}}/ranger/rc.conf"

- name: Symlink scope.sh
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/ranger/scope.sh"
    dest: "{{user_config_dir}}/ranger/scope.sh"
