- import_tasks: arch.yml
  when: ansible_facts['os_family']|lower|replace(' ', '') == 'archlinux'

- import_tasks: fedora.yml
  when: ansible_facts['pkg_mgr'] == 'dnf'

- name: Symlink .gitconfig
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/git/gitconfig"
    path: "{{user_home}}/.gitconfig"

- name: Copy .git-user
  copy:
    src: git-user
    dest: "{{user_home}}/.git-user"
    force: no

- name: Symlink global .gitignore
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/git/gitignore"
    path: "{{user_home}}/.gitignore"
