- name: Install hub
  become: true
  pacman:
    name: hub
    state: latest

- name: Copy .gitconfig
  template:
    src: gitconfig
    dest: "{{user_home}}/.gitconfig"

- name: Symlink global .gitignore
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/git/gitignore"
    path: "{{user_home}}/.gitignore"
