- name: Install dependencies
  become: true
  dnf:
    name:
      - ruby
      - ruby-devel
      - libicu
      - libicu-devel
      - zlib
      - zlib-devel
      - make
      - cmake
      - gcc
      - gcc-c++
      - openssl
      - libgit2
      - libgit2-devel
      - redhat-rpm-config

- name: Make gollum directory
  become: true
  file:
    path: /var/gollum
    state: directory
    owner: fox  # Run Gollum as `fox` since we autopush
    group: fox

- name: Link gollum config
  file:
    state: link
    force: true
    src: "{{dotfiles_dir}}/configs/ishtar/gollum/config.rb"
    path: /var/gollum/config.rb

- name: Make gollum install directory
  file:
    path: /var/gollum/gem/
    state: directory

- name: Install gollum
  become: true
  gem:
    name: gollum
    user_install: no
    install_dir: /var/gollum/gem

- name: Install omnigollum
  become: true
  gem:
    name: omnigollum
    user_install: no
    install_dir: /var/gollum/gem

- name: Make user systemd units directory
  file:
    path: "{{user_config_dir}}/systemd/user/"
    state: directory

- name: Link gollum service
  file:
    state: link
    force: true
    src: "{{dotfiles_dir}}/configs/ishtar/gollum/gollum.service"
    path: "{{user_config_dir}}/systemd/user/gollum.service"
