- import_tasks: gollum.yml

- name: Install nginx
  become: true
  dnf:
    name:
        - nginx

- name: Fix httpd
  become: true
  seboolean:
    persistent: yes
    name: httpd_can_network_connect
    state: yes

- name: Give up
  become: true
  selinux_permissive:
    domain: httpd_t
    permissive: yes


- name: Make nginx log directory
  become: true
  file:
    path: /var/log/nginx/
    state: directory
    owner: nginx
    group: nginx
    recurse: true

- name: Copy nginx config
  become: true
  file:
    state: link
    force: true
    src: "{{dotfiles_dir}}/configs/ishtar/nginx/nginx.conf"
    path: "/etc/nginx/nginx.conf"
    owner: nginx
    group: nginx

- name: Add nginx config for proxying Cockpit
  become: true
  file:
    state: link
    src: "{{dotfiles_dir}}/configs/ishtar/nginx/cockpit.conf"
    path: "/etc/nginx/conf.d/cockpit.conf"

- name: Add nginx config for serving the root cert
  become: true
  file:
    state: link
    src: "{{dotfiles_dir}}/configs/ishtar/nginx/cacert.conf"
    path: "/etc/nginx/conf.d/cacert.conf"

- name: Reload nginx
  become: true
  systemd:
    name: nginx
    state: reloaded
