- import_tasks: gollum.yml

- name: Install nginx
  become: true
  dnf:
    name:
        - nginx

- name: Fix httpd
  seboolean:
    persistent: yes
    name: httpd_can_network_connect
    state: yes

- name: Add nginx config
  become: true
  file:
    state: link
    force: true
    src: "{{dotfiles_dir}}/configs/ishtar/nginx/nginx.conf"
    path: "/etc/nginx/nginx.conf"

- name: Add nginx config for proxying Cockpit
  become: true
  file:
    state: link
    src: "{{dotfiles_dir}}/configs/ishtar/nginx/cockpit.conf"
    path: "/etc/nginx/default.d/*.conf"
