- import_tasks: arch.yml
  when: ansible_facts['os_family']|lower|replace(' ', '') == 'archlinux'

- name: Copy alacritty config
  template:
    src: alacritty.yml
    dest: "{{user_config_dir}}/alacritty/"
