- name: Get rid of vim if exists
  become: true
  pacman:
    name: vim
    state: absent
    extra_args: --recursive

- name: Install nvim, pynvim, nodejs
  become: true
  pacman:
    name:
      - neovim
      - python-pynvim
      - nodejs
