- name: Get rid of vim if exists
  become: true
  dnf:
    name:
      - vim
      - vim-minimal
    state: absent

- name: Install nvim, python3-neovim, nodejs
  become: true
  dnf:
    name:
      - neovim
      - python3-neovim
      - nodejs
