- import_tasks: arch.yml
  when: ansible_facts['os_family']|lower|replace(' ', '') == 'archlinux'

- import_tasks: vi-symlink.yml

- import_tasks: fedora.yml
  when: ansible_facts['pkg_mgr'] == 'dnf'

- name: Symlink init.vim
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/nvim"
    path: "{{user_config_dir}}/nvim"

- name: Install nvim plugins
  command: nvim --headless +PlugInstall +UpdateRemotePlugins +qa
